### ISSUE TITLE
ProtHint hanging at 99.9% during alignment

### ISSUE THREAD

**Issue by tkjmk** [gatech-genemark/ProtHint#14]
Hi,

I have ran BRAKER 2.1.5 on several _Drosophila_ genomes and apart from occasional segmentation faults on joingenes, it seems to be working fine.

However, there is one genome _Drosophila simulans_ WXD1 that I am unable to get to run. This is because it keeps hanging on the ProtHint step of BRAKER. This is with both pipeline C and pipeline D. See the last few lines of an example log file:

> [Fri Aug 28 06:30:01 2020] 322123/323741 (99.5%) pairs aligned
> [Fri Aug 28 06:30:18 2020] 322447/323741 (99.6%) pairs aligned
> [Fri Aug 28 06:30:41 2020] 322770/323741 (99.7%) pairs aligned
> [Fri Aug 28 06:31:05 2020] 323094/323741 (99.8%) pairs aligned
> [Fri Aug 28 06:31:27 2020] 323418/323741 (99.9%) pairs aligned

This happens every time I run BRAKER on this genome, and it just hangs there until I cancel the job.

I have tried running ProtHint 2.4.0 separately and it also hangs at 99.9%.
The command I run is:
`prothint.py  --geneMarkGtf ${indir}GeneMark-ES/genemark.gtf ${indir}genome.fa ${indir}proteins.fa`

All those input files are from the failed BRAKER runs. The protein input is from odb10 Arthropoda.

The headers of the file are

> \>dsimWXD1_0
> \>dsimWXD1_1
> \>dsimWXD1_2
> ...
> \>dsimWXD1_214
> \>dsimWXD1_215

I have made sure there are no ambiguous characters: R|Y|W|S|M|K|H|B|V|D
The genome is softmasked, and characters in the sequence are A|C|T|G|a|c|t|g|N
216 scaffolds, 146.8 MB.

I can share the FASTA file if required. I believe it's specific to this genome, as this has not happened with the other 6 genomes I have processed and used in the same way.

Many thanks for any help or insights you are able to provide.

**Comment by tkjmk** [comment]
I just wanted to add that I've tried with ProtHint 2.5.0 and it is still hanging at 99.9%.

> [Mon Aug 31 19:19:13 2020] Enqueueing pair 322125/323743 (99.5%). Est. time left: 00:00:33 (hh:mm:ss)
> [Mon Aug 31 19:19:22 2020] Enqueueing pair 322449/323743 (99.6%). Est. time left: 00:00:27 (hh:mm:ss)
> [Mon Aug 31 19:19:28 2020] Enqueueing pair 322772/323743 (99.7%). Est. time left: 00:00:20 (hh:mm:ss)
> [Mon Aug 31 19:19:31 2020] Enqueueing pair 323096/323743 (99.8%). Est. time left: 00:00:14 (hh:mm:ss)
> [Mon Aug 31 19:19:36 2020] Enqueueing pair 323420/323743 (99.9%). Est. time left: 00:00:07 (hh:mm:ss)

I have also tried on a single core (locally and submitted to cluster), and on multiple cores. All are hanging at 99.9% with this particular genome.

**Comment by tomasbruna** [comment]
Hello @tkjmk,

thank you for the detailed problem description!

I think the problem here is that Spaln gets stuck with a specific gene-protein pair. These errors are super rare and also hardware-dependent but I should probably add some sort of a timeout so that ProtHint does not get stuck like this.

Let's try the following workaround to fix your issue:

Can you check the folder `Spaln` in the working directory of your ProtHint run? There should be the following files: `nuc_N`,  `prot_N`, and `nuc_N_prot_N`. Try to locate the stuck Spaln process, with

    ps aux | grep spaln

It should look similar to this

    /path/to/ProtHint/bin/../dependencies/spaln -Q3 -LS -pw -S1 -O1 -l 16158 nuc_N prot_N

Then you can open the problematic `prot_N` file (the one which is stuck) and see which particular protein is problematic. Removing that protein from input fasta with proteins should solve the issue.

Thank you for taking the time to test this!

Best regard,
Tomas

**Comment by tkjmk** [comment]
Thank you for the quick response @tomasbruna 

ProtHint has now completed for this genome. There were two problematic proteins, and once both were removed it stopped hanging at 99.9%.

Once again thanks a lot!
