### ISSUE TITLE
Speed of the process

### ISSUE THREAD

**Issue by skyungyong** [gatech-genemark/ProtHint#9]
Hi, 

I am running ProtHint with 22 threads for a masked fungal genome that is about 45Mb in size and contains 12,000 genes. Each run seems to take about 7 hours, much slower than 3 hours for Drosophila given as an example. 

It only took 20 minutes to finish both GeneMark-ES and Diamond. Spaln is taking the rest of the time. Is it typical? When I check the CPU usage with top during the Spaln run, only a single one seems to be occupied. I wonder whether this process supports multi-threading and I can speed this process up. 

Thank you for your help!

**Comment by tomasbruna** [comment]
Hello @skyungyong,

the Spaln part of ProtHint is parallelized and it indeed should run much faster on a fungal genome like yours.

That said, I experienced a similar problem before -- with a large number of short genes which are easy to align, the time it takes to call Spaln within ProtHint can be longer than the actual alignment time. This can lead to poor utilization of CPUs. I fixed this problem in commit https://github.com/gatech-genemark/ProtHint/commit/1d932f2918bf4a3e98301086f52d7872a4d11ed1, please try to clone the latest version of ProtHint from the master branch to see if this speeds up your run.

Also, I added an option to run GeneMark-ES in its fungal mode. This should increase ProtHint accuracy a bit. Please, try running ProtHint with `--fungus` option.

Best,
Tomas

**Comment by skyungyong** [comment]
Hi @tomasbruna,

Thank you for the work! The running time reduced from 7 hours to 3.5 hours. Would there be any parameters I can tune to speed up the process a bit more in my computer setting? I'd like to run this for a few hundred genomes and wonder whether I can reduce the computing time. 

Best wishes,

**Comment by tomasbruna** [comment]
Hi @skyungyong,

I am glad the fix had an effect, thanks for your report. Fungal genomes should still be a bit faster, can you make sure you have fast disk access? It can make a big difference...

You can also speed the process up by changing the `--maxProteinsPerSeed N` parameter. By default, this is set to 25. Using 5 instead, for example, would make the program ~5x faster. The cost is a decrease of Sensitivity. You can check out the [supplementary materials of the GeneMark-EP+ paper](https://academic.oup.com/nargab/article/2/2/lqaa026/5836691#203497589) (Page 12, Figure S9) to get an idea of how much Sensitivity you would be losing.

For example, the intron Sensitivity was decreased by ~5 percentage points (or ~7 percentage points for high-confidence introns) when 5 instead of was 25 was used on _D. melanogaster_.

![Sn-Sp](https://user-images.githubusercontent.com/6759211/87453867-34080900-c5d1-11ea-8bd7-9f56eb3c351a.png)


Best regards,
Tomas

**Comment by skyungyong** [comment]
Hi @tomasbruna,

Thank you for pointing those out for me! With the --maxProteinsPerSeed 5 parameters, the running time decreased to 35 min. 

I am using a shared computer cluster. When I ran software directly in the assigned node, the running time was only 30 min with 25 maxProteinPerSeed! I think this was the major problem. Thank you for your advice!
